import ThemeSwitcher from "./ThemeSwitcher";
import { AuthProvider } from "./authProvider";
import "./globals.css";
import Providers from "./providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Providers>
            <ThemeSwitcher />
            {children}
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
