import { NextAuthProvider } from "./Providers";
import ThemeSwitcher from "./ThemeSwitcher";
import "./globals.css";
import Providers from "./theme-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <Providers>
            <ThemeSwitcher />
            {children}
          </Providers>
        </NextAuthProvider>
      </body>
    </html>
  );
}
